### ISSUE TITLE
Username and password hb-service

### ISSUE THREAD

**Issue by homebraj** [lwitzani/homebridgeStatusWidget#1]
Hello 👋 
I want to create the widget but I don’t know what is the username and password of hb-service, I tryed the username and password of the Raspberry Pi and of homebridge but it don’t work, can you help me please ?
Thanks

**Comment by lwitzani** [comment]
Hi,
do have https://github.com/oznu/homebridge-config-ui-x in use ? It is the username & password that you also use to access this app via a browser. Even if you disabled authentication, for the widget you need enter these infos.

Hope that helps.

**Comment by homebraj** [comment]
I have change the default username/password so I tried the default username/password and the actual username/password and I deleted the >< but it doesn’t work

**Comment by lwitzani** [comment]
I‘m not sure if i understand what you are trying to tell me. The default credentials of Homebridge-config-ui-x are 
username: admin  
Password: admin

If you changed these, you need to enter the changed credentials of course. Later today i will add the possibility to not use credentials if the security is set to none. Maybe this will help you (only if you have security off in the ui)

**Comment by lwitzani** [comment]
I intergrated support for authentication mode 'none' in homebridge-config-ui-x! so if that was your problem now only enter the URL and it should work

**Comment by homebraj** [comment]
Sorry but the SD Card of my Raspberry Pi is crashed
When I will reinstall the OS ( 64-bit when it will possible ) and, I will see it, Thank you 😉

**Comment by homebraj** [comment]
It doesn’t want to work 😩
To explain to you, when I reinstalled Homebridge, I changed the username and the password but I also entered the commands "sudo passwd homebridge" and "sudo adduser homebridge sudo" in the terminal of the raspberry pi to be able to control it via the terminal of homebridge interface, the 1st command is used to modify the terminal password because the password that must be entered when carrying out a "sudo" command does not work  not for me and the 2nd is used to allow the use the "sudo" command with homebridge
I don't know if this is the cause of the problem, do you think this is it, please ?

**Comment by lwitzani** [comment]
The widget has nothing to do with user or admin password of the actual machine. 

The widget uses the same credentials that are necessary to login to the hombridge-config-ui-x provided UI in the browser


Definitely not the problem of the widget 😅

**Comment by lwitzani** [comment]
is the issue still present? Can we close it?
