### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by gecko74** [lwitzani/homebridgeStatusWidget#11]
Hi

I have this error on my iPad. 
![5036BCA5-E281-41FA-982E-3CEF7335C9C2](https://user-images.githubusercontent.com/60316229/99658902-5ff43900-2a60-11eb-85b1-f7497433eabc.png)

On my iPhone run thia script without problems. 

Thanks
Marc

**Comment by lwitzani** [comment]
Can you go into you icloud drive files and look in the scriptable folder and then in the homebridgeStatus folder. There should be a hbLogo file. My guess is that is has not been downloaded yet. So press the download button and run the script again

**Comment by gecko74** [comment]
Ok yes. It works now. Thank you very much.

**Comment by lwitzani** [comment]
Nice 👍🏻
