### ISSUE TITLE
[Enhancement] custom notifications

### ISSUE THREAD

**Issue by sw33tT** [lwitzani/homebridgeStatusWidget#12]
Is it possible to add the status notifications to the configuration mechanism and save the „custom“ notifications to the JSON file for easy restore or update.

'Homebridge Status changed:'
'Your Homebridge instance stopped 😱'
'Your Homebridge instance is back online 😁'
'Update available for Homebridge 😎'
'Homebridge is now up to date ✌️'
'Update available for one of your Plugins 😎'
'Plugins are now up to date ✌️'
'Update available for Node.js 😎'
'Node.js is now up to date ✌️'

This would make it more easy to change text or language for custom notifications.

Thanks

**Comment by lwitzani** [comment]
Yeah thanks for the proposal 👍🏻 Can do it

**Comment by sw33tT** [comment]
thanks for your work on that really great scriptaple-widget

**Comment by lwitzani** [comment]
hey, can you get the newest code and check if everything is working? You config that you currently have will be removed and a new one created (because structure changed). Now you can set basically everything :D even color etc

**Comment by sw33tT** [comment]
It worked like a charm for me: i created the new JSON file and it loading without any issues.

The JSON file has all edits i made.

**Comment by lwitzani** [comment]
Nice 👍🏻
