### ISSUE TITLE
Exception on launch

### ISSUE THREAD

**Issue by fullphat** [lwitzani/homebridgeStatusWidget#13]
Hi there!

Triple-checked all info, but get the following on launch:

![29258EF0-25A4-435C-92B7-AC7C75970540](https://user-images.githubusercontent.com/11242840/99871893-bcc53000-2bd5-11eb-9e8e-5664d3e8c287.jpeg)

Thoughts?

**Comment by lwitzani** [comment]
Hi,
so i had already like at least 3 users with that problem. The solution that solved their issue was to update all parts. Like e.g. update homebridge-config-ui-x and homebridge and node.js. My guess is that homebridge-config-ui-x is not up to date ? Please also get the latest script code or if you already had it delete the json files in your icloud folder that the script creates (just to make sure that these are not the problem)

**Comment by fullphat** [comment]
Thanks for the reply - Homebridge and node.is all up to date but still getting the error!

**Comment by lwitzani** [comment]
With Homebridge, do you mean the actual nom package homebridge ? Or so you mean both of the packages homebridge-config-ui-x and homebridge ? My guess is still that config-ui-x is not updated. 


Otherwise maybe this video setting everything up helps? 

https://www.dropbox.com/s/4jjhax6bmfcbnwl/setup_homebridge_widget.MP4?dl=0

**Comment by fullphat** [comment]
I meant everything 😊 HomeBridge, node.js, and homebridge-config-ui-x all were up to date.

However, my HomeBridge Pi crashed this morning and after rebuilding, reinstalling and restoring everything from backup I've just tried this widget and it now works! 🤣

**Comment by lwitzani** [comment]
Haha good :D ! So i‘ll close the issue 👍🏻
