### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by SzilagyiR** [lwitzani/homebridgeStatusWidget#14]
Hi!

First of all thanks for your work, it is amazing!

I have a problem, the widget not update itself, only when I run the scipt again.

**Comment by lwitzani** [comment]
When you have it set up as widget only iOS knows when it is updated again. You need to wait. 
From my experience, you can force update the widget by changing the provided parameter to an invalid value and then changing it back to a valid value. So every time you change a the parameter, it updates directly afterwards. 

If you have the newest version of the script you might have to run the script once while the variable overwritePersistedConfig is set to true.

**Comment by SzilagyiR** [comment]
Thank!

It will update every 20 minutes, I am not patience enought :)

**Comment by lwitzani** [comment]
So can i close this issue?

**Comment by SzilagyiR** [comment]
Yes, thanks!
