### ISSUE TITLE
Error: The data couldn’t be read because it isn’t in the correct format.

### ISSUE THREAD

**Issue by scorpioRED** [lwitzani/homebridgeStatusWidget#15]
What is wrong?
I have just edited on the script my user name/password and external IP with ”http://...”

**Comment by lwitzani** [comment]
Is it the first time you use the script? 
Usually this error is shown if your homebridge-config-ui-x is not up to date. Can you update it and check again?

**Comment by scorpioRED** [comment]
Yes! After updating it’s work!
Thanks
