### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by sschuste** [lwitzani/homebridgeStatusWidget#16]
Hi,

is a connection via SSL supposed to work? I use homebridge-config-ui-x with a self-signed certificate but I'm not able to connect.

X UI-Service not reachable!
* Server started? _Yes_
* UI-Service process started? _Yes_
* Server-URL https://homepi.lan:8088 correct? _Yes, can be opened in Safari_
* Are you in the same network? _Not me, but my iPhone is. :-D_
* Did you doublecheck you configuration? _Yes, 11 times._

Any idea?

**Comment by lwitzani** [comment]
Hm unfortunately i can‘t say yes or no. But if you can access it in safari with that url i don‘t see a reason why it would not work with the widget. Maybe increase the timeout variable? It should be 2seconds at the moment. Maybe it takes longer than that to reach your system via the real internet

**Comment by lwitzani** [comment]
Did you get it to work with https? 
Is there anything left with this issue or can we close it?

**Comment by sschuste** [comment]
It doesn't work, but you can close this issue.

**Comment by jonatan1979** [comment]
Can confirm it does not work with https. But why was this issue closed? Can't it be fixed to work with https?

**Comment by lwitzani** [comment]
Closed it since i wont look into it
