### ISSUE TITLE
Error on line 252:42. 

### ISSUE THREAD

**Issue by rafalkuziola** [lwitzani/homebridgeStatusWidget#17]
I have a problem... Error on line 252:42.  

I copy code from homebridgeStatusWidget.js to scriptable, then I change only configurationFileName, username, password and URL. 

![IMG_6752](https://user-images.githubusercontent.com/74871652/99915912-ffd2f080-2d06-11eb-983e-4273dc820c45.jpeg)

**Comment by lwitzani** [comment]
Please check this closed issue as it might be the same: https://github.com/lwitzani/homebridgeStatusWidget/issues/11

**Comment by rafalkuziola** [comment]
THX. It works now. Thank you very much.
