### ISSUE TITLE
Is the widget working only when connected to the same network?

### ISSUE THREAD

**Issue by Ludelag** [lwitzani/homebridgeStatusWidget#19]
Hello, good morning, As I wrote yesterday UI-Service not reachable! #18, the widget finally was working good, this morning as well, but when I left home and get into the the office wifi, the widget is not reporting any more, I have it connected to the cloud.

Is it supported or I have to be in the same net to get the information?

Thnak you

**Comment by lwitzani** [comment]
If you should be able to reach your system from anywhere than maybe you need to increase the timeout variable in the script. It is currently 2seconds. Maybe increase this value and try again

**Comment by Ludelag** [comment]
Hello, Yes I have to 10 since yesterday, but it is not reachable. I increase to 15 and the same result

**Comment by lwitzani** [comment]
And when you copy the url from the script into the browser you can access your homebridge-config-ui-x ? 

The widget is not explicitly constructed to work outside the same network, so i don‘t know if it should work in your concrete case

**Comment by Ludelag** [comment]
Not really, to access I should be in my network. Other wise I should use a Public IP. I think it is clear. Is not possible to access from different network. Any way getting back I will check if the access thru the widget works, then I will have all clear. But to all the Hombridge plugin device services in IOs I can access being outside.

**Comment by lwitzani** [comment]
Yes you probably have an apple tv or a homepod or an ipad setup as you hub for homekit, that‘s why you can control your devices. But that is something completely different. And if you cant access the homebridge-config-ui-x with the url you use in the script then it of course won‘t work especially if it is not a public ip but a local one...

**Comment by Ludelag** [comment]
Yes, I thought so.

**Comment by Ludelag** [comment]
Confirmed! it works only being in the same network.

**Comment by lwitzani** [comment]
The „only“ part is not entirely true. It depends on your concrete system setup. It should technically work if you can publicly access your homebridge-config-ui-x instance

**Comment by Ludelag** [comment]
Sorry, I close it by accident. How can I make it public access? Public IP?

**Comment by lwitzani** [comment]
I guess public ip yes.

**Comment by Ludelag** [comment]
I need to open ports to have the access to the Config-UI-X. I think will stay where I am. Only monitoring  the info when I am in the same network. Thank you. Your widget is amazing!!!
