### ISSUE TITLE
inital run fails with Error on line 671:16: TypeError:

### ISSUE THREAD

**Issue by runrennerrun** [lwitzani/homebridgeStatusWidget#20]
Hi, 

I get the following error here whilst running the inital setup: 
Error on line 671:16: TypeError: undefined is not a function (near '...plugin of pluginsData...')

what I am doing wrong ? :-) 

many thanks in advance, 
Rob

**Comment by lwitzani** [comment]
Is this a duplicate of https://github.com/lwitzani/homebridgeStatusWidget/issues/3 ?

Please check all the closed issues

**Comment by runrennerrun** [comment]
ooookay - thats it. thx!
