### ISSUE TITLE
Use with not admin iser

### ISSUE THREAD

**Issue by j3r3m067** [lwitzani/homebridgeStatusWidget#21]
Hello,
It would be better if we could use the script with a non-admin user for security reasons.

**Comment by lwitzani** [comment]
Did you try it? If the API allows non admins to get the information then it already should work... If it doesnt work then it doesn’t work without admin rights ;)

**Comment by lwitzani** [comment]
Do you have an update on this or can i close this issue?

**Comment by djsmix** [comment]
can confirm it works with a user without admin rights, just tested it 👍

**Comment by lwitzani** [comment]
Thanks for the info 👍🏻
