### ISSUE TITLE
Have wish, is it possible to implement in the widget a button to the Webseite.

### ISSUE THREAD

**Issue by testpaul999** [lwitzani/homebridgeStatusWidget#26]
Hello,
 is it possible to implement in the widget a button to the Webseite.
Like at the symbol from Homebridge upper left side.

Thx

**Comment by lwitzani** [comment]
This is not necessary since Scriptable itself already allows to specify a url that is opened when taping the widget


![Uploading 826F8821-A334-4259-9DED-2723CB6BF5B6.png…]()

**Comment by lwitzani** [comment]
![3975E8CA-8C13-444D-B094-11F6AFCDC88D](https://user-images.githubusercontent.com/26573718/100737454-7c836000-33d4-11eb-8c73-015e790c74da.png)

**Comment by testpaul999** [comment]
Thx, greate and so easy. 👍🏻

Viele Grüße

Jens-Uwe Franz

Am 01.12.2020 um 12:55 schrieb lwitzani <notifications@github.com>:

﻿

[3975E8CA-8C13-444D-B094-11F6AFCDC88D]<https://user-images.githubusercontent.com/26573718/100737454-7c836000-33d4-11eb-8c73-015e790c74da.png>

**Comment by lwitzani** [comment]
👍🏻 I‘ll close this issue
