### ISSUE TITLE
Today’s Homebridge UI update stopped widget and shown error 828:38.

### ISSUE THREAD

**Issue by Terminator0007** [lwitzani/homebridgeStatusWidget#27]

**Comment by Terminator0007** [comment]
Error 828:38 after today's HB UI update.

**Comment by lwitzani** [comment]
Please state the whole error and line here since i can’t know which version of the code you have...is the script code up to date?

**Comment by Terminator0007** [comment]
![image](https://user-images.githubusercontent.com/64287824/100785314-c0945600-3410-11eb-9c15-6d3a68a4794e.jpeg)

**Comment by Terminator0007** [comment]
Where can I find version inside of code ?

**Comment by lwitzani** [comment]
The last update of the script was 5days ago. Did you update the code in the last 5 days? I guess you are using it via scriptdude so i guess it is updated.
 I think this could be an issue with having multiple devices with the same iCloud account. Can you try giving the variable const NOTIFICATION_JSON_FILE_NAME at around line 143 a different content(only on the device where it is not working)? (E.g. ‚test.json‘ )

**Comment by Terminator0007** [comment]
Ok, understand now. I bought new iPhone, download backup from Cloud and everything stopped because older phone still active with apps. I will try what you suggested me.

**Comment by Terminator0007** [comment]
There is a screenshot from log.![image](https://user-images.githubusercontent.com/64287824/100791964-36e98600-341a-11eb-981b-673f61a262b8.jpeg)

**Comment by lwitzani** [comment]
yes perfect i know what the problem is. I'll fix it, give me a couple minutes

**Comment by Terminator0007** [comment]
🙏👍

**Comment by lwitzani** [comment]
i updated the code. Can you check if the problem is still there ?

**Comment by Terminator0007** [comment]
Your medicine killed poison.... all is ok, thanks a lot and Kind Regards 💪

**Comment by lwitzani** [comment]
Nice, i‘ll close this issue then
