### ISSUE TITLE
Homebridge installed on Docker

### ISSUE THREAD

**Issue by trolli-ch** [lwitzani/homebridgeStatusWidget#28]
I moved the Homebridge from RPI to Synology Docker.
I changed the IP but it still shows the old IP in widget. I dont know where it gets the old one. In the script its just once...

Is it at least working with Docker ? Homebridge UI is active, but I am not really sure about the required service.

Thanks !

**Comment by lwitzani** [comment]
It uses the old one because of the configuration mechanism. You must run the script once with overwritePersistedConfig set to true. This will save the current state. Afterwards when you are done configuring set it back to false.

**Comment by trolli-ch** [comment]
OK. I read somewhere about it 👍 
Thanks for quick response.
Widget looks great !

**Comment by lwitzani** [comment]
Is this issue still relevant or can we close it :) ?
