### ISSUE TITLE
Exception Line 337:16  TypeError

### ISSUE THREAD

**Issue by bubffm** [lwitzani/homebridgeStatusWidget#3]
I am getting the following error when the script is checking wehter the plugins are up to date:

Exception Occurred:
Error on line 337:16: TypeError: 
undefined is not a function (near
'....plugin of pluginsData....')

Any idea why this might be or ehat this actually means?

thanks

NB:
Its having trouble with this code somewhere:

**Comment by bubffm** [comment]
`async function getPluginsUpToDate(token) {
    const pluginsData = await fetchData(token, pluginsUrl);
    if (pluginsData === undefined) {
        return undefined;
    }
    for (plugin of pluginsData) {
        if (plugin.updateAvailable) {
            return false;
        }
    }
    return true;
}`

**Comment by raphb83** [comment]
Same here...

**Comment by raphb83** [comment]
Made timeout longer 5 seconds - now getting new error:
Error on line 160:51: ReferenceError: Can't find variable: getPluginsUpToDate

**Comment by bubffm** [comment]
Seems also related to PluginUpToDate routine....

**Comment by lwitzani** [comment]
Do you have the latest code? (I updated it often today)
Do you have the matching versions of all systems? (Check the readme for the versions)

**Comment by bubffm** [comment]
yes, only downloaded an hour or so ago.   I have UI X Version  4.33.0  which is one update later than what you have...

**Comment by lwitzani** [comment]
Hm i did not test it yet with the newest update. I need to sleep now :D will test it tomorrow with the newest homebridge-config-ui-x version

**Comment by bubffm** [comment]
Sure, no rush

**Comment by lwitzani** [comment]
I just updated the UI. Everything works normal for me. Some reddit user had the same problem but it was solved by updating all the parts, if i remember right

**Comment by bubffm** [comment]
What do you mean by "updating all the parts"?

**Comment by lwitzani** [comment]
With all parts i mean
- scriptable app (& use a iphone)
- ios
- the script itself
- homebridge
- homebridge-config-ui-x


A reddit user said that ipad widgets in general dont work as good as on the iPhone yet. 

Also line 142 is a comment at the latest version of the script so doesnt seem like you have the latest script version...

**Comment by bubffm** [comment]
All my parts are on latest version.  I do use iCloud drive.

**Comment by lwitzani** [comment]
Which devices do you use? 
The logo image is loaded from the internet.  So does the internet on the devices work 😅? Guess it does

**Comment by bubffm** [comment]
Yep Internet sure does work. I use an iPhone 11 Pro.

**Comment by lwitzani** [comment]
I really have no clue why it wouldn’t work. I also have a 11 pro! Many reddit user wrote it works. So i only can assume that either i inserted a bug somewhere in the latest code or some configuration on your part is not as it should be. Did you try the LOCAL fileManagerMode ?

**Comment by MichaelLiatowitsch** [comment]
It happened to me awell, the issue was a wrong username/password in the config.
check the logs of homebridge when you run the script, mine complained wrong username/password.

**Comment by bubffm** [comment]
Thanks @MichaelLiatowitsch .  This was the hint that solved it.  I actually thought I was using the same password for the UI X as for my homebridge, but not so....

Changing the password, and the script runs.  Everybody else having the issue should try this as well.

**Comment by lwitzani** [comment]
Thanks for the info @MichaelLiatowitsch ! Glad it works now :D 👍🏻
