### ISSUE TITLE
Auto-select LAN or WAN

### ISSUE THREAD

**Issue by Samueleitor6** [lwitzani/homebridgeStatusWidget#30]
Hi!! And thanks for this fantastic plugin!

You could put two variables, one as a local network, i.e: 192.168.1.20 and another as DDNS such as the No-IP services, and so if the first address fails, try the second, and if not, it returns that the host is unreachable.

At the moment, in order not to modify anything, I have duplicate script with both directions, but if it were possible in the same one, having both would be ideal!

thank you!!

**Comment by lwitzani** [comment]
Hi, thanks for the proposal. But why don’t you just use only the URL of the DDNS then? I mean this should also work if you are in your network...so i don’t really see why you would need two

**Comment by Samueleitor6** [comment]
oh! Should it work on my own network?

Well, I will have to check some configuration on my router, because it tells me that it is inaccessible if I am on LAN ...

Thank you so much!!

**Comment by Samueleitor6** [comment]
Ok, I have searched the internet and it seems that it is because my router does not support "NAT loopback", there are many people with other apps Edith rey dame issue because of that 😭.
From te LAN they cannot use their DDNS address.

So for the moment I have to configure two instances for LAN and WAN in my case .

Thank you anyway!!
