### ISSUE TITLE
UI-Service not reachable

### ISSUE THREAD

**Issue by abattistin** [lwitzani/homebridgeStatusWidget#31]
I copied and pasted the code into Scriptable, I putted my IP address, the user and password, when I run the script I get that message

**Comment by lwitzani** [comment]
url must be http://<your ip>:<your port>

**Comment by abattistin** [comment]
![Uploading 103475315...] yes! That's what I have there and the user and password that I use to sign in

**Comment by abattistin** [comment]
![image](https://user-images.githubusercontent.com/50064631/103475388-d8406f00-4e00-11eb-8122-681d299c2088.png)

**Comment by lwitzani** [comment]
Looks good to me! Are you actually in the same network^^? can you go in the browser on your phone and open the page with this url?

**Comment by abattistin** [comment]
Yes I can same network

**Comment by abattistin** [comment]
![image](https://user-images.githubusercontent.com/50064631/103475543-070b1500-4e02-11eb-8120-bfadc3c74ae2.jpeg)

**Comment by lwitzani** [comment]
Please check in the ios settings, in the section of the scriptable app, if the app has the right „Local Network“

**Comment by abattistin** [comment]
🤦🏻‍♂️ yep that what the issue! Thanks for the support

**Comment by lwitzani** [comment]
Ncr 👍🏻
