### ISSUE TITLE
Notification to update Node.js, when it's already up to date

### ISSUE THREAD

**Issue by derekschinke** [lwitzani/homebridgeStatusWidget#33]
Received a notification that there was an update to Node.js. Checked my setup, and I'm already on v14.15.4 'Fermium' (LTS). However, the widget shows `⚠️ Node.js UTD` instead of the green checkmark.

**Comment by lwitzani** [comment]
Does it still show that an update is available after the script ran again? I just use the provided data from homebridge-config-ui-x, so if this says there is an update but there is actually not then i cant do anything ;)
