### ISSUE TITLE
"Pretty-printing" Stored configuration into JSON (overwritePersistedConfig = true)

### ISSUE THREAD

**Issue by DannyBoyKN** [lwitzani/homebridgeStatusWidget#34]
Could it be possible to add a 3rd argument to JSON.stringify and pretty-print the configuration, for better readability and editing ?
Eg.:

```js
...
function persistObject(fm, object, path) {
    let raw = JSON.stringify(object, null, 2);
    fm.writeString(path, raw);
}
...
```

Refer to official [doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify)

**Comment by lwitzani** [comment]
I Can look into it

**Comment by DannyBoyKN** [comment]
Top :ok_hand:
