### ISSUE TITLE
update changelog??

### ISSUE THREAD

**Issue by henkied** [lwitzani/homebridgeStatusWidget#35]
I see there are some updates https://github.com/lwitzani/homebridgeStatusWidget/blob/main/CHANGELOG.md

how do I install these updates or does it work automatically?

**Comment by lwitzani** [comment]
if you have https://scriptdu.de/#installation and installed my script via Sriptdude then you must run the Scriptdude script and press update in the UI that is shown to you. 

if you installed it manually via copying the code from https://raw.githubusercontent.com/lwitzani/homebridgeStatusWidget/main/homebridgeStatusWidget.js and pasting it into a new script inside your app then you must do it exactly as last time (switching out the existing code with the new code). Maybe you will need to enter credentials and the URL again

**Comment by henkied** [comment]
i see thx a lot!!
