### ISSUE TITLE
Error: Request timeout.

### ISSUE THREAD

**Issue by thorstenman** [lwitzani/homebridgeStatusWidget#38]
I had to set up my Homebridge from scratch. Everything's working but the widget. Also set up the Scriptable widget and configured starting from zero. I unfortunately always get an error message showing that the request runs into a timeout. Tried different variants iCloud or local, added a new admin user, checked IP/port - so far I was not lucky. You have an idea?

**Comment by lwitzani** [comment]
does it work if you increase the timeout variable?

**Comment by thorstenman** [comment]
Solved, but root cause was different. Authentication was not working properly. Thanks for your quick response - and this super cool widget!
