### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by michel0271** [lwitzani/homebridgeStatusWidget#4]
Hello, I can't get the widget to work although I entered everything correctly.

Can it be that the widget does not work with Homebridge Vers. 1.2.3 and Homebridge UI 4.33.0?

thx

**Comment by lwitzani** [comment]
Hi,
i just tested it with Homebridge at version 1.2.3 and Homebridge UI 4.33.0 and it works well. 

Probably there is some configuration still wrong on your side :).

you can try:
- triple check username / password / URL
- increase the timeout variable whose default is 1
- set the filemanagerMode to LOCAL (default is ICLOUD)


What is the error that you get ? What device do you use?

**Comment by michel0271** [comment]
Hi,

the error is like this: https://github.com/lwitzani/homebridgeStatusWidget/blob/main/notAvailable_purple.jpg

i have all check, username, passwort an URL, correct

**Comment by michel0271** [comment]
now it works, sorry
