### ISSUE TITLE
Open url won’t work with iPadOS 15

### ISSUE THREAD

**Issue by testpaul999** [lwitzani/homebridgeStatusWidget#40]
Hi,

I use the public beta from iPadOS 15 and I can’t put the Url into the widget field anymore.

**Comment by lwitzani** [comment]
Can you post a screenshot? Is this a problem of iOS 15? Or of the Scriptable app itself? Or of my Script?

**Comment by testpaul999** [comment]
Yes, sure here they are.
I don’t now who the issue is located with iPadOS 14 it will run fine.
![19F55F56-6DC6-4E4D-9D23-5D1FA399EFC8](https://user-images.githubusercontent.com/35597907/126194857-ed283fd0-4cc0-4808-9fe9-78541f01c108.png)
![B818810D-4FD8-44FB-9060-B1067E63960F](https://user-images.githubusercontent.com/35597907/126194870-02f0d796-fa74-47a1-9a45-7ba513315108.png)
![3DB9AED9-2914-4345-B492-BCB6CCDE6A48](https://user-images.githubusercontent.com/35597907/126194877-0675a769-6b77-435b-a6d6-a37b3e557f0a.png)

**Comment by lwitzani** [comment]
Can you scroll inside of this window? Because there must be the „Parameter“ section at the bottom. It must look like this 
![Uploading 0D17DE28-04F6-465F-8E12-C05EBE3A67F0.png…]()

**Comment by testpaul999** [comment]
This field are empty.
I‘ll always open the website with the widget.
Like this old wish from me here.
„Have wish, is it possible to implement in the widget a button to the Webseite. #26“

**Comment by lwitzani** [comment]
If you have the Parameter section, then you must enter the credentials und the url there. In a specific format! please check the read.me on how to configure the widget. 
If you enter the URL like you did in the Url section and configured „when interacting -> open Url“, this will really open a webpage with your configured url, but this has nothing to do with my script configuration ;). E.g. if you change „open url“ to „open script“ then wen you tap the widget, the Script in Scriptable opens…

**Comment by testpaul999** [comment]
Ok so this is different from iPadOS 14 to 15?
Yes I see the parameter field but I‘ll only have to open the webpage.
So did you see a solution?
 I don’t want to have this „ If you have the Parameter section, then you must enter the credentials und the url there. In a specific format! please check the read.me on how to configure the widget.“

regards

**Comment by lwitzani** [comment]
So as far as i can tell, nothing is wrong with iOS 15 or the Scriptable app or my script. It’s still the same as ios 14. You just need to configure it properly in my opinion. 
here is one way to configure the widget: 
![0A16FFFC-5CC9-47FD-A3A4-F0530127A445](https://user-images.githubusercontent.com/26573718/126212938-f52b4d10-a9df-4398-8a46-c0e0a5b413ef.png)

**Comment by testpaul999** [comment]
No I can’t follow your mind.
I have Test this with my iPhone and iOS 14 there it works like expected.
Put only the url at the field push the widget and the website will be opened.
 

https://user-images.githubusercontent.com/35597907/126293427-f8610c5e-16f7-4ce4-b50c-e7d7c982fe63.MOV
I use the same script I’ve copy it with all entry’s in it.

**Comment by lwitzani** [comment]
Oh wait. You just want this feature that when you tap the widget the webpage opens? Seems i misunderstood something here. I thought you can‘t manage to get the widget itself running. 

All right, so this actually really does not have anything to do with my script :). This is a feature of Scriptable itself. You can do this (open an URL) with any widget of Scriptable. So the problem here is either ios15 or Scriptable. Sorry i misunderstood

**Comment by testpaul999** [comment]
😀 not a problem thx for your patience.
Have also open a feedback to apple 😉

you can close here
