### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by many7695** [lwitzani/homebridgeStatusWidget#43]
I’m not sure what has happened but I haven’t gotten it to work again for the last month

**Comment by lwitzani** [comment]
I guess you need to give me more information here or i can‘t help you. I got no problem using it. I did not yet test it with the newest homebridge version. What did you change in your setup?

**Comment by many7695** [comment]
> I guess you need to give me more information here or i can‘t help you. I got no problem using it. I did not yet test it with the newest homebridge version. What did you change in your setup?

I haven’t changed anything from my setup, it was working great before the last month, the widget says error  the request has timed out

**Comment by many7695** [comment]
Thanks that worked
