### ISSUE TITLE
help on installation

### ISSUE THREAD

**Issue by MaurizioB84** [lwitzani/homebridgeStatusWidget#45]
Hi, I readed all readme but I don't understand in which way I can install and configure it, someone can help me?

**Comment by lwitzani** [comment]
Hi, you need the iOS App Scriptable and copy the script code either manually inti a new script in the app or install it via the the website scriptdu.de as shown here: https://www.dropbox.com/s/4jjhax6bmfcbnwl/setup_homebridge_widget.MP4?dl=0

this shows a complete install from scratch.
