### ISSUE TITLE
Same network 

### ISSUE THREAD

**Issue by entoryFB** [lwitzani/homebridgeStatusWidget#5]
unfortunately it doesn't work for me.
your widget also works if the raspbery is connected via ethernet?
 or is it because I have HB version 1.2.3.

**Comment by lwitzani** [comment]
I tested it with HB version 1.2.3 and it works fine. 
Yes i also have my Raspberry Pi connected via ethernet.
the URL is basically the 'http://<ip to your Raspberry Pi>:<port to your HB Config UI X instance>'
username and password are the ones that you use to login to your HB Config UI X instance (if your credentials don't work logging in to the page on a regular browser, you don't have the right credentials ;) )

What is the error message for you/what does not work?

**Comment by entoryFB** [comment]
> I tested it with HB version 1.2.3 and it works fine.
> Yes i also have my Raspberry Pi connected via ethernet.
> the URL is basically the 'http://:'
> username and password are the ones that you use to login to your HB Config UI X instance (if your credentials don't work logging in to the page on a regular browser, you don't have the right credentials ;) )
> 
> What is the error message for you/what does not work?


oh dear
had forgotten http://
many thanks for the great widget

**Comment by DJay-X** [comment]
@lwitzani Just want to say a big thank you for this awesome script. 
Thanks for investing your time, sharing with the community and the ongoing development.
You already have a big fanbase. :) 👍 
All the best to you.

**Comment by lwitzani** [comment]
thanks for the nice words @DJay-X ! Glad to make some people happy with my widget :) !
will close this issue now :)
