### ISSUE TITLE
Exception Occurred

### ISSUE THREAD

**Issue by djsmix** [lwitzani/homebridgeStatusWidget#56]
2023-11-04 19:47:38: Error on line 809:16: TypeError: undefined is not a function (near '...plugin of pluginsData...')

What can i do?

**Comment by djsmix** [comment]
Nvm, The account should be admin :-)

**Comment by lwitzani** [comment]
😅 nice. The account name should be the name of a user that has admin rights, yes. If you only have the user „admin“ then yeah, it must be „admin“ ;)
