### ISSUE TITLE
'Undefined is not a  function' Error

### ISSUE THREAD

**Issue by xcytre** [lwitzani/homebridgeStatusWidget#57]
I'm getting this error:

Error on line 809:16: TypeError: undefined is not a function (near '...plugin of pluginsData...')

What am I doing wrong?

**Comment by lwitzani** [comment]
Hey :) 
Could you search in the other issues (incl. closed ones) for „undefined is not“ and check the responses there first? This message came up more often with several cases, e.g. not using a user that has admin rights or people not copying the whole script when installing it…

thanks

**Comment by xcytre** [comment]
I apologize for not checking the closed cases!  I was not using an admin account.  It worked once I corrected that!

Thank you, sir!

**Comment by lwitzani** [comment]
No worries, glad i could help and that it works 🥳 

cheers
