### ISSUE TITLE
2024-07-28 14:56:55: Error on line 808:17: TypeError: undefined is not a function (near '...plugin of pluginsData...')

### ISSUE THREAD

**Issue by CryptoKnight360** [lwitzani/homebridgeStatusWidget#62]
Hello. I been trying to configure this plugin for days. I have triple checked all my configs and all seems well. As soon as I enter the URL, username, and login info I get this error message: **2024-07-28 14:56:55: Error on line 808:17: TypeError: undefined is not a function (near '...plugin of pluginsData...')**. When I enter the default json file, the widget shows up, but of course it does not connect. 

This is how my config file looks after editing. Of course I replaced the username and password with (*). Also, since I'm using MacOS and iOS I have ensured to disable "Smart Quotes" on the keyboard settings since this is known to cause issues when copying/pasting code on MacOS/iOS.

// Variables used by Scriptable.
// These must be at the very top of the file. Do not edit.
// icon-color: blue; icon-glyph: magic;
// Check the readme at https://github.com/lwitzani/homebridgeStatusWidget for setup instructions, troubleshoots and also for updates of course!
// Code Version: 16.11.2022
// *********
// For power users:
// I added a configuration mechanism so you don't need to reconfigure it every time you update the script!
// Please check the readme for instructions on how to use the persist mechanism for the configuration
let configurationFileName = 'blackconfig.json' // change this to an own name e.g. 'configBlack.json' . This name can then be given as a widget parameter in the form 'USE_CONFIG:yourfilename.json' so you don't loose your preferred configuration across script updates (but you will loose it if i have to change the configuration format)
const usePersistedConfiguration = true; // false would mean to use the visible configuration below; true means the state saved in iCloud (or locally) will be used
const overwritePersistedConfig = true; // if you like your configuration, run the script ONCE with this param to true, then it is saved and can be used via 'USE_CONFIG:yourfilename.json' in widget params
// *********

const CONFIGURATION_JSON_VERSION = 3; // never change this! If i need to change the structure of configuration class, i will increase this counter. Your created config files sadly won't be compatible afterwards.
// CONFIGURATION //////////////////////
class Configuration {
    // you must at least configure the next 3 lines to make this script work or use credentials in parameter when setting up the widget (see the readme on github)
    // if you don't use credentials, just enter the URL and it should work
    // as soon as credentials + URL are correct, a configuration is saved and then used. to make changes after that set overwritePersistedConfig to true
    hbServiceMachineBaseUrl = 'http://192.168.1.10:8581'; // location of your system running the hb-service, e.g. http://192.168.178.33:8581
    userName = '*****'; // username of administrator of the hb-service
    password = '*************************'; // password of administrator of the hb-service
    notificationEnabled = true; // set to false to disable all notifications

    This is the code in lines 807-812 that it seems to be complaining about: 

   }
    for (plugin of pluginsData) {
        if (CONFIGURATION.pluginsOrSwUpdatesToIgnore.includes(plugin.name)) {
            log('You configured ' + plugin.name + ' to not be checked for updates. Widget will show that it\'s UTD!');
            continue;
        }

**Comment by lwitzani** [comment]
Hi,

so the credentials you use work when using the usual webpage to login to homebridge-config-ui right? 

Otherwise maybe something went wrong when copying the code manually, maybe you should try the installation mechanism with scriptdu.de which is basically another script that handles the installation of scripts in general.

otherwise you can browse through the closed issues and search for your error because there where issues with similar errors („pluginsData“…) which usually were not a problem with the script. 

Oootherwise maybe this 4 year old video helps setting up the stuff (using scriptdu.de)
https://www.dropbox.com/scl/fi/doc59060auu4z1721dlp1/setup_homebridge_widget.MP4?rlkey=5y5fb9hm9hx8hphn99tq7bezm&dl=0


Hope that helps?

**Comment by CryptoKnight360** [comment]
I have tried that method as well. It installs perfectly, once I enter the credentials it complains about the same exact line/s of code. And yes, the credentials work fine when logging in via browser.  This error code persists no matter what installation method I try.

**Comment by lwitzani** [comment]
Does your user have admin rights in the hb config Ui? Maybe make sure that it has.
It should actually be as simple as editing 4 lines of code (url, username, password + setting overwritePersistedConfig to true ) and then the script should already work when executed inside the scriptable app (as seen in the video)

**Comment by CryptoKnight360** [comment]
That was EXACTLY the problem. I created a new user that didn't utilize 2FA, but I did not give that user admin permissions. As soon as I gave it those permissions, the widget immediately worked!! Thanks for helping out, this was driving me insane for a few days now!!

**Comment by lwitzani** [comment]
Nice! Glad we figured it out. Have a good one!
