### ISSUE TITLE
Cant connect to my homebridge running in a docker

### ISSUE THREAD

**Issue by ikorbln** [lwitzani/homebridgeStatusWidget#7]
Hello,
I run my homebridge in a docker in my Synology NAS, but i can do what i want i cant connect to it. So is there any restriction running it like that??

**Comment by lwitzani** [comment]
No that should not be a restriction!
Go on your iphone in your browser and access the the homebridge-config-ui-x webpage. If this works, then the widget should also work since the URL and the credentials you need for the widget are the same as the credentials you need to login on the homebridge-config-ui-x page.

**Comment by ikorbln** [comment]
I can open the config-ui page, but with port 8080. With port 8581 i got no response.
And when i try the port 8080 with the widget i get an error message "the data cant be read, they have the wrong format"

**Comment by lwitzani** [comment]
Why would you put the whole adress http://192.168.232.210:8080/api/status/cpu ? This adress directly speaks tocthe endpoint of the UI API and if you did not get a Authentication Token before, then you get „not authorized“. That’s exactly shat my script does for you. You only need to enter http://192.168.232.210:8080/ in my widget. 

Yes the ports can be different. For you it is 8080 then, that‘s totally fine. 

And if you still get „the data cant be read, they have the wrong format“ after the credentials are correct, then you probably need to check the versions of everything (the UI, Homebridge itself, your scriptable app, ios). Other users with the same problem had it fixed after updating

**Comment by ikorbln** [comment]
i put the whole adress just for testing what happend. I will check all versions and test again. Thx so far.

**Comment by ikorbln** [comment]
sorry, it was my fault. i had the ui version 4.27.1. now it is version 4.33 and it works. thanks for help!
