### ISSUE TITLE
Homebridge with „noAuth“ doesn‘t work

### ISSUE THREAD

**Issue by Frank-Friemel** [lwitzani/homebridgeStatusWidget#8]
The Widget should consider Homebridge Users with Auth set to ‚none‘. The token Url is then: /api/auth/noauth

**Comment by lwitzani** [comment]
Hell yes! I had ‚none‘ myself but couldnt get it to work without credentials :D didnt know about the  /api/auth/noauth endpoint. Seems that‘s something i overlooked! Thanks so much for that info. Will have a look and integrate it

**Comment by lwitzani** [comment]
Well shame on me here. It‘s basically the third line of the API at the Authentication section 😂🤷🏼‍♂️

**Comment by lwitzani** [comment]
I integrated it. Can you verify it is working ?

**Comment by Frank-Friemel** [comment]
Works now with ‚noauh‘. Keep up the good work
